### PR TITLE
Tester/nxtests

### PR DESCRIPTION
**Pull request by takumuguti**
#27

### CODE REVIEW

**Comment by takumuguti** [comment]
@MatthewGotte could you please help with the linting of the signed.component.ts its saying something about an empty constructor.

**Comment by MatthewGotte** [comment]
@takumuguti I have made a commit to the branch which should fix it

**Comment by takumuguti** [comment]
@MatthewGotte  Awesome looks good.

**Review by MatthewGotte — APPROVED** [review]
@takumuguti it has fixed the issues with the lint

**Pull request merged**
